### ISSUE TITLE
Windows 8.1 + Minecraft 1.8.7/1.6.4 表示无法通过 SendKeys "^v" 黏贴内容

### ISSUE THREAD

**Issue by LastAvenger** [m13253/minecraft-chat-helper#7]
另, 置剪贴板内容可以这么写(Win 7 以上限定):

```vbs
WshShell.Run "cmd.exe /c echo " & str & "| clip.exe", 0, false
```

**Comment by m13253** [comment]
似乎是有人发现 Minecraft 1.8 不能用 Ctrl-V 按钮了。
我本来以为是 OS X only。原来现在是全平台的问题。

因为我现在因为学业不再玩 Minecraft 了，所以麻烦你个人修复它，并且给我发送 Pull Request。
谢谢。

**Comment by LastAvenger** [comment]
Windows 下的, 我试了一下, 表示 vbs 没办法实现了.
Linux 下的话仙子有解, 我哪天改一改.

**Comment by m13253** [comment]
> Linux 下的话仙子有解, 我哪天改一改.

Linux 的话你试试看 #5 所说的 xdotool 直接输入汉字。
