### ISSUE TITLE
好像会多出一个t

### ISSUE THREAD

**Issue by YumeMichi** [m13253/minecraft-chat-helper#9]
输入框的内容会自动在前面多出一个t
![](https://blog.ikke.moe/img/steam.png)

**Comment by m13253** [comment]
> 输入框的内容会自动在前面多出一个t

这个T是 Minecraft 的聊天快捷键。
如果你要在别的软件下使用，比如 Steam，改一下源代码，把输入 T 的那行（33行）删掉即可。
（反正我也是用这货对付 Steam 的，然而 Steam 聊天窗口中文乱码你知道怎么解决吗？）
![screenshot from 2015-12-22 01-36-07](https://cloud.githubusercontent.com/assets/1808930/11937015/a1dc58ca-a84c-11e5-8b2e-8f3019760092.png)

**Comment by YumeMichi** [comment]
应该是字体的问题 你试试删除掉Steam自带的字体~/.font 再安装个wqy-zenhei试试
